# Site settings
title: codenavneet.github.io
description: 
baseurl: 
relative_url: True
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Navneet Singh
user_description: .
user_title: ProblemSolving || Android
email: navneet555k@gmail.com
twitter_username: navneet555k
github_username:  navneet555k

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
